/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rismaintanw
 */
public class pemilihandokter extends javax.swing.JFrame {

    /**
     * Creates new form pemilihandokter
     */
    public pemilihandokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(163, 11, 152, 14);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 43, 53, 14);

        jLabel3.setText("Identitas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 68, 43, 14);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 91, 27, 14);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 122, 33, 14);

        jLabel6.setText("Usia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(97, 148, 20, 14);

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(54, 174, 63, 14);

        jLabel8.setText("Golongan Darah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 200, 77, 14);

        jLabel9.setText("Status");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(86, 226, 31, 14);

        jLabel10.setText("Kewarganegaraan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(29, 252, 88, 14);

        jLabel11.setText("Waktu Praktek");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(47, 278, 70, 14);

        jLabel12.setText("Dokter Spesialis");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(42, 304, 75, 14);
        getContentPane().add(jtxtnama);
        jtxtnama.setBounds(163, 88, 152, 20);
        getContentPane().add(jtxtalamat);
        jtxtalamat.setBounds(163, 119, 152, 20);
        getContentPane().add(jtxtusia);
        jtxtusia.setBounds(163, 145, 152, 20);

        jtxtjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtjenisActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtjenis);
        jtxtjenis.setBounds(163, 171, 152, 20);
        getContentPane().add(jtxtgol);
        jtxtgol.setBounds(163, 197, 152, 20);
        getContentPane().add(jtxtstatus);
        jtxtstatus.setBounds(163, 223, 152, 20);

        jtxtkewar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtkewarActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtkewar);
        jtxtkewar.setBounds(163, 249, 152, 20);
        getContentPane().add(jtxtwaktu);
        jtxtwaktu.setBounds(163, 275, 152, 20);
        getContentPane().add(jtxtspesial);
        jtxtspesial.setBounds(163, 301, 152, 20);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah satu--", "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(163, 37, 129, 20);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtjenisActionPerformed

    private void jtxtkewarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtkewarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtkewarActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
        if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){
            jtxtnama.setText("DR. Farras Yassar ");
            jtxtalamat.setText("Jl. Surabaya 16, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("A");
            jtxtstatus.setText("Belum Menikah ");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Umum");
            jtxtwaktu.setText(" Pagi (07.00-15.00)");
        }
        else if(jconadokt.getSelectedItem().equals("DR. Dian Sikahita")){
            jtxtnama.setText("DR. Dian Sikahita");
            jtxtalamat.setText("Jl. Veteran 3, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Gigi");
            jtxtwaktu.setText(" Sore (16.00-22.00)");
        }
        else if(jconadokt.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            jtxtnama.setText("DR. Harun Ulum Fajar");
            jtxtalamat.setText("Jl. Bandung 9, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("B");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Gizi");
            jtxtwaktu.setText(" Malam (22.00-06.00)");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemilihandokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
